language: go

matrix:
  include:
  - go: "1.15.x"
  - go: "1.16.x"


env:
  - GO111MODULE=on

install: true

before_script:
  - go install github.com/onsi/ginkgo/ginkgo
  - go install honnef.co/go/tools/cmd/staticcheck

script:
  - MIRBFT_TEST_CONTEXT_TIMEOUT=180s MIRBFT_TEST_STRESS_TICK_INTERVAL=1000ms ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace
  - staticcheck ./...
